### ISSUE TITLE
Incompatibility with prettier 3.0

### ISSUE THREAD

**Issue by pshurygin** [NiklasPor/prettier-plugin-organize-attributes#17]
The plugin is incompatible with prettier v3. Are there any plans to support v3 anytime soon?
[Here](https://github.com/prettier/prettier/wiki/How-to-migrate-my-plugin-to-support-Prettier-v3%3F) is a migration guide for plugin authors.

**Comment by NiklasPor** [comment]
Looks very doable, I think it might be just the version increment and some minor adjustments.

**Comment by mbenzenhoefer** [comment]
I also need that update, can we somehow support you here? @NiklasPor

**Comment by NiklasPor** [comment]
I'm gonna start with the migration on this plugin today and then continue to the more complex packages 👀🫡

**Comment by NiklasPor** [comment]
Starting with `prettier-plugin-organize-attributes@1.0.0` we're supporting `prettier: "^3.0.0"`. Beware that you need to add now the plugin **explicitly** to your prettier config (😢):

```json
{
  "plugins": ["prettier-plugin-organize-attributes"]
}
```

The new config requirement originates from this issue: https://github.com/prettier/prettier/issues/13729

**Comment by NiklasPor** [comment]
If anyone has any problems feel free to write here, or create a new issue 👍

**Comment by dtslvr** [comment]
It works like a charm. Thank you very much @NiklasPor 🙂

**Comment by minijusl** [comment]
@NiklasPor is it backwards compatible with version 2?

**Comment by NiklasPor** [comment]
@minijusl I didn't test it, but I'd expect it **not** to be, as Prettier 3 included breaking API changes. Just stay on the old version if you're using Prettier 2 currently 👍
