### ISSUE TITLE
Add ability to ignore a file

### ISSUE THREAD

**Issue by danjor** [NiklasPor/prettier-plugin-organize-attributes#9]
Hello,

Could it be possible to add a feature to ignore a file so imports will not be ordered ?
For instance, in my project we used previously "prettier-plugin-organize-imports", and they added a feature later to ignore a file from being formatted by the plugin, by adding the following comment :

// organize-imports-ignore

Full explaination could be found [here](https://github.com/simonhaenisch/prettier-plugin-organize-imports/issues/4#issuecomment-646685901), and related commit also [here](https://github.com/simonhaenisch/prettier-plugin-organize-imports/pull/8/commits/71ce231ad5790e1b8af40f5af0dbc240ab86a1d4), that consists only of having an if condition to check if the file constains that comment.

Thank you.

**Comment by NiklasPor** [comment]
For the whole file or for a section / single tag?
There's also always the option if just disabling the sorting for specific files inside the .prettierrc. 

If you're interested in that I can give you an example.

**Comment by danjor** [comment]
Thanks for your reply.

We finally manage to ignore some files completly by using the .prettierignore and .prettierrc

**Comment by NiklasPor** [comment]
If you only want to disable sorting for a specific file (or file-matcher) you can do it in the following way:

```json
{
  "overrides": [
    {
      "files": "unsorted.html",
      "options": {
        "attributeGroups": ["$DEFAULT"],
      }
    }
  ]
}
```

I'll mark this as resolved for now, if there are any other questions just comment here or in a new issue :)
